#!/usr/bin/with-contenv bash

# set default values for variables
declare -A SNIPT_CONF
SNIPT_CONF[SITE_HOST]=${SITE_HOST:-snipt.example.com}

if [ ! -f "/config/settings_local.py" ]; then
	mv /defaults/settings_local.py /config/
	SECRET_KEY=$(date +%s | sha256sum | base64 | head -c 32)
	sed -i 's|changeme|'${SECRET_KEY}'|g' /config/settings_local.py

	# sed in values or skip if value not set
	for KEY in "${!SNIPT_CONF[@]}"; do \
	if [[ ${SNIPT_CONF[$KEY]} == "" ]]; then \
	:
	else sed -i 's|{{'$KEY'}}|'${SNIPT_CONF[$KEY]}'|g' /config/settings_local.py
	fi
	done
fi

rm /app/snipt/settings_local.py
ln -s /config/settings_local.py /app/snipt/settings_local.py

mv /defaults/uwsgi.ini /app/snipt/uwsgi.ini > /dev/null 2>&1

mkdir /data

# permissions
chown -R abc:abc \
	/app/snipt \
	/config \
	/data

cd /app/snipt || exit

exec \
	s6-setuidgid abc /usr/bin/python3 ./manage.py migrate
